# Generated by Django 4.0 on 2022-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_exportal_image1_exportal_image2_exportal_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internal',
            name='line',
            field=models.BooleanField(default=False),
        ),
    ]
