# Generated by Django 4.0 on 2022-01-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('location', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('stone_type', models.CharField(max_length=125)),
                ('country', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=125)),
                ('province', models.CharField(max_length=125)),
                ('state', models.CharField(max_length=125)),
            ],
        ),
    ]
