# Generated by Django 4.0 on 2022-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsave',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
